const fs = require("fs-extra");
const path = require("path");
const { buildSnapshot } = require("../snapshot");
const { mergeThreeWay } = require("../merge/three-way");
const {
  diffDependencies,
  planDependencyChanges,
} = require("./deps");

const PACKAGE_JSON = "package.json";

const OUTCOMES = {
  CREATE: "create",
  MERGED: "merged",
  CONFLICT: "conflict",
  ALREADY: "already-applied",
  OCCUPIED: "occupied",
  DROPPED: "dropped",
};

// The feature's footprint: every path the two snapshots disagree about. Files
// they agree on are none of `add`'s business, which is also what keeps a
// project generated by an older CLI from quietly absorbing template changes -
// those differences live between versions, not between configs.
function footprint(base, theirs) {
  const paths = new Set([...Object.keys(base.files), ...Object.keys(theirs.files)]);
  return [...paths]
    .filter(filePath => base.files[filePath] !== theirs.files[filePath])
    .filter(filePath => filePath !== PACKAGE_JSON)
    .sort();
}

async function planFile(filePath, { projectPath, base, theirs, labels }) {
  const target = path.join(projectPath, filePath);
  const onDisk = await fs.pathExists(target);
  const inBase = Boolean(base.files[filePath]);
  const inTheirs = Boolean(theirs.files[filePath]);

  if (!inTheirs) {
    // The feature's own files never vanish like this today, but a future one
    // could stop shipping something. Removing it is not ours to decide.
    return { path: filePath, outcome: OUTCOMES.DROPPED };
  }

  const wanted = await theirs.read(filePath);

  if (!onDisk) {
    return { path: filePath, outcome: OUTCOMES.CREATE, content: wanted };
  }

  const existing = await fs.readFile(target, "utf8");
  if (existing === wanted) {
    return { path: filePath, outcome: OUTCOMES.ALREADY };
  }

  if (!inBase) {
    // The feature wants to create a file the project already has at that path,
    // and there is no common ancestor to merge from.
    return { path: filePath, outcome: OUTCOMES.OCCUPIED, content: wanted };
  }

  const merge = mergeThreeWay({
    base: await base.read(filePath),
    ours: existing,
    theirs: wanted,
    labels,
  });

  return {
    path: filePath,
    outcome: merge.clean ? OUTCOMES.MERGED : OUTCOMES.CONFLICT,
    content: merge.merged,
    theirs: wanted,
    conflicts: merge.conflicts,
  };
}

async function buildAddPlan({ projectPath, currentConfig, nextConfig, labels }) {
  const base = await buildSnapshot(currentConfig, { label: "add-base" });
  const theirs = await buildSnapshot(nextConfig, { label: "add-next" });

  try {
    const files = [];
    for (const filePath of footprint(base, theirs)) {
      files.push(
        await planFile(filePath, { projectPath, base, theirs, labels })
      );
    }

    const dependencies = planDependencyChanges(
      await fs.readJson(path.join(projectPath, PACKAGE_JSON)),
      diffDependencies(
        await base.readJson(PACKAGE_JSON),
        await theirs.readJson(PACKAGE_JSON)
      )
    );

    // Xcode project files cannot be written from a snapshot - the object ids
    // would not be this project's. Comparing them with the ids blanked does
    // say whether the feature touched the project at all, which is the
    // difference between sending the user to Xcode and staying quiet.
    const xcode = [
      ...new Set([...Object.keys(base.xcode), ...Object.keys(theirs.xcode)]),
    ]
      .filter(filePath => base.xcode[filePath] !== theirs.xcode[filePath])
      .sort();

    // What the baseline becomes afterwards: the hash of what a clean
    // generation with the new config produces, never the hash of what ends up
    // on disk. A file the user keeps their own version of has to stay marked
    // as diverged, or the next upgrade would overwrite it silently.
    const baselineUpdates = {};
    for (const item of files) {
      if (theirs.files[item.path]) {
        baselineUpdates[item.path] = theirs.files[item.path];
      }
    }
    baselineUpdates[PACKAGE_JSON] = theirs.files[PACKAGE_JSON];

    return { files, dependencies, xcode, baselineUpdates };
  } finally {
    await base.dispose();
    await theirs.dispose();
  }
}

module.exports = { buildAddPlan, footprint, OUTCOMES, PACKAGE_JSON };
