const fs = require("fs-extra");
const path = require("path");
const crypto = require("crypto");
const { MANIFEST_FILENAME } = require("./schema");

// Dropped wherever they appear in the tree: dependency trees, build output and
// IDE/tool state. None of it is ours to migrate, and `assets` is the user's own
// artwork, which no template upgrade should ever touch.
const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "Pods",
  "build",
  "vendor",
  "assets",
  ".gradle",
  ".cxx",
  ".idea",
  ".kotlin",
  "xcuserdata",
  "DerivedData",
]);

// Regenerated by the toolchain, or - link-assets-manifest.json - full of ids we
// produce with Math.random(). A hash of either says nothing about whether the
// user changed anything.
//
// local.properties and .xcode.env.local are machine-specific and gitignored:
// they hold an Android SDK path and a node binary path, and postinstall rewrites
// the latter on every install. Hashing them would report a freshly cloned
// project as modified on a teammate's machine.
const SKIP_FILES = new Set([
  MANIFEST_FILENAME,
  "local.properties",
  ".xcode.env.local",
  // The user's Firebase credentials, copied in from wherever they downloaded
  // them. They are not template output, their paths are deliberately kept out
  // of the manifest, and no upgrade has any business touching them.
  "google-services.json",
  "GoogleService-Info.plist",
  "pnpm-lock.yaml",
  "package-lock.json",
  "yarn.lock",
  "Podfile.lock",
  "Gemfile.lock",
  "link-assets-manifest.json",
  ".DS_Store",
]);

const SKIP_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".svg",
  ".ico",
  ".icns",
  ".ttf",
  ".otf",
  ".woff",
  ".woff2",
  ".jar",
  ".aar",
  ".zip",
  ".keystore",
  ".jks",
  ".pdf",
  ".mp4",
  ".iml",
]);

function isSkippedDir(name) {
  return SKIP_DIRS.has(name) || name.endsWith(".xcassets");
}

function shouldHashFile(relativePath) {
  const segments = relativePath.split(/[\\/]/).filter(Boolean);
  if (segments.length === 0) {
    return false;
  }

  const name = segments[segments.length - 1];
  if (segments.slice(0, -1).some(isSkippedDir)) {
    return false;
  }
  if (SKIP_FILES.has(name)) {
    return false;
  }

  return !SKIP_EXTENSIONS.has(path.extname(name).toLowerCase());
}

async function collectFiles(rootPath, relativeDir, collected) {
  const entries = await fs.readdir(path.join(rootPath, relativeDir), {
    withFileTypes: true,
  });

  for (const entry of entries) {
    const relative = relativeDir ? `${relativeDir}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      if (!isSkippedDir(entry.name)) {
        await collectFiles(rootPath, relative, collected);
      }
      continue;
    }

    // Symlinks are deliberately skipped: hashing the target would record state
    // that lives outside the project.
    if (entry.isFile() && shouldHashFile(relative)) {
      collected.push(relative);
    }
  }

  return collected;
}

async function hashFile(filePath) {
  const content = await fs.readFile(filePath);
  return crypto.createHash("sha1").update(content).digest("hex");
}

// Keys come back sorted so a manifest rewrite produces a readable git diff
// instead of a reshuffled blob.
async function hashProjectFiles(projectPath) {
  const collected = await collectFiles(projectPath, "", []);
  collected.sort();

  const hashes = {};
  for (const relative of collected) {
    hashes[relative] = await hashFile(path.join(projectPath, relative));
  }
  return hashes;
}

module.exports = {
  SKIP_DIRS,
  SKIP_FILES,
  SKIP_EXTENSIONS,
  shouldHashFile,
  hashFile,
  hashProjectFiles,
};
