const fs = require("fs-extra");
const {
  MANIFEST_FILENAME,
  manifestPath,
  validateManifest,
} = require("./schema");

async function hasManifest(projectPath) {
  return fs.pathExists(manifestPath(projectPath));
}

// Returns null when the project simply has no manifest (generated by an older
// CLI, or never generated by us at all) and throws when one exists but cannot
// be trusted - the caller must not treat a broken manifest as an absent one.
async function readManifest(projectPath) {
  const filePath = manifestPath(projectPath);
  if (!(await fs.pathExists(filePath))) {
    return null;
  }

  let data;
  try {
    data = await fs.readJson(filePath);
  } catch (error) {
    throw new Error(`${MANIFEST_FILENAME} is not valid JSON: ${error.message}`);
  }

  return validateManifest(data);
}

module.exports = { hasManifest, readManifest };
